# Generated by Codex

import apps.admin_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AiVrCourseContent',
            fields=[
                ('id', models.CharField(default=apps.admin_panel.models.generate_uuid_hex, max_length=32, primary_key=True, serialize=False)),
                ('curriculum_id', models.CharField(blank=True, default='', max_length=255)),
                ('curriculum_name', models.CharField(max_length=255)),
                ('chapter_title', models.CharField(max_length=255)),
                ('chapter_order', models.PositiveIntegerField(default=0)),
                ('section_title', models.CharField(max_length=255)),
                ('section_order', models.PositiveIntegerField(default=0)),
                ('resource_type', models.CharField(choices=[('video', '课程视频'), ('ppt', '课程PPT'), ('test', '在线测验'), ('correct', '在线批改'), ('ai', 'AI助学'), ('vr', 'VR资源')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_ai_vr_course_content',
                'ordering': ['chapter_order', 'section_order', 'resource_type', 'sort_order', 'create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='aivrcoursecontent',
            index=models.Index(fields=['curriculum_name'], name='admin_ai_v_curric_93f351_idx'),
        ),
        migrations.AddIndex(
            model_name='aivrcoursecontent',
            index=models.Index(fields=['curriculum_id'], name='admin_ai_v_curric_1ed448_idx'),
        ),
        migrations.AddIndex(
            model_name='aivrcoursecontent',
            index=models.Index(fields=['resource_type'], name='admin_ai_v_resour_d634e6_idx'),
        ),
    ]
