# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('admin_panel', '0001_create_ai_vr_course_content')]

    operations = [
        migrations.CreateModel(
            name='UserAccountControl',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'admin_user_account_control'},
        ),
    ]
